### ISSUE TITLE
Can Dopamine support the distributed DDPG algorithm?

### ISSUE THREAD

**Issue by Haizhoudu** [google/dopamine#10]
As above?

**Comment by psc-g** [comment]
At this moment Dopamine only comes with 4 value-based agents: DQN, C51, Rainbow, and IQN.
We kept it this way for simplicity and ease of us.
We may add more agent types as we see the demand grow, so stay tuned!

**Comment by micici** [comment]
Qustion as the tille ,I hava instaled all of the requirement package，but  the error I can`t fix it. Otherwise  I execute the ‘python tests/atari_init_test.py’ the error is ‘no moudle named dopamine.atari’
Thanks!
