### ISSUE TITLE
What the error 'Failed building wheel for atari-py？'

### ISSUE THREAD

**Issue by micici** [google/dopamine#11]
Qustion as the tille ,I hava installed all of the requirement package，but  the error I can`t fix it. Otherwise  I execute the ‘python tests/atari_init_test.py’ the error is ‘no moudle named dopamine.atari’
Thanks!

**Comment by psc-g** [comment]
can you please provide the commands you ran to install, as well as the command you use to run the test?

**Comment by micici** [comment]
Tanks for answering.The situation sa follow：
OS：Ubuntu 18.04.1LTS
Used Commands (part of ):
pip install virtualenv
pip cmake zlib1g-dev
pip install absl-py atari-py gin-config gym opencv-python tensorflow
//sudo apt-get  install XX  ,the error was '‘unable to locate '...
The first command  I used was follow the ReadMe Doc,'sudo apt-get install virtualenv', but unfortunately，the error message was ‘unable to locate the virtualenv’,I solved  the error used the 'pip install xx' commands ,meanwhile installed the other packages which virtualenv depend on.
Only the ‘pip install atrati-py’ and can`t been installed.
Tanks!

**Comment by psc-g** [comment]
you typed in `pip install atrati-py`
just making sure it's not a typo, the command should be: `pip install atari-py`

**Comment by micici** [comment]
I used the command 'pip install atari-py' before,and try it again.
-------------------------------
pip install atari-py
Looking in indexes: 
Collecting atari-py
  Downloading https:/atari-py-0.1.1.tar.gz (760kB)
    100% |████████████████████████████████| 768kB 10.1MB/s 
Requirement already satisfied: numpy in /usr/local/lib/python2.7/dist-packages (from atari-py) (1.14.5)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from atari-py) (1.11.0)
Building wheels for collected packages: atari-py
 Running setup.py bdist_wheel for atari-py ... error
------------------------------------------
Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: atari-py
  Running setup.py install for atari-py ... error

=.=!!!

**Comment by micici** [comment]
The problem was caused by gcc, and has been solved, thanks for your help.

**Comment by DianeSoHungry** [comment]
@micici I came across the same problem. Do you mind share us how to solve this gcc problem? I had gcc installed on my MAC.

**Comment by sidistic** [comment]
Try installing cmake. It worked for me once I did that.

**Comment by lucasresck** [comment]
I wasn't allowed to build atari-py too:

Building wheels for collected packages: atari-py
Building wheel for atari-py (setup.py) ... error

** a lot of logs **

ERROR: Failed building wheel for atari-py
  Running setup.py clean for atari-py
Failed to build atari-py
Installing collected packages: opencv-python, atari-py, Pillow
    Running setup.py install for atari-py ... error

** a lot of logs **

So I did `pip install cmake` and I think it solved it.

**Comment by bdytx5** [comment]
> Try installing cmake. It worked for me once I did that.

heres a quick way to do so
`
brew install cmake 

`

**Comment by SolowomanYudachi** [comment]
> I wasn't allowed to build atari-py in Ubuntu 19.10 inside a conda environment:
> 
> Building wheels for collected packages: atari-py
> Building wheel for atari-py (setup.py) ... error
> 
> ** a lot of logs **
> 
> ERROR: Failed building wheel for atari-py
> Running setup.py clean for atari-py
> Failed to build atari-py
> Installing collected packages: opencv-python, atari-py, Pillow
> Running setup.py install for atari-py ... error
> 
> ** a lot of logs **
> 
> So I did `pip install cmake` and I think it solved it.
> 
> Edit: I realized that it works in Python 3.7, but not in Python 3.8.

Same, I was using Python 3.9 with my miniconda environment and I searched for all python version available in conda and roll back to 3.7, now Atari installation works fine!

**Comment by microgold** [comment]
installing cmake was definitely the key, 
I aksi had to install both gcc  and g++ with apt-get and set the paths correctly for environment variables CC and CXX.  CC needs to point to the gcc compiler and CXX needs to point to the g++ compiler
