### ISSUE TITLE
utils/agent_visualizer.py scipy 

### ISSUE THREAD

**Issue by Alex2782** [google/dopamine#112]
"scipy.misc.imsave" was removed in scipy version 1.3
--> `pip install scipy==1.2.1`

https://docs.scipy.org/doc/scipy/reference/release.1.3.0.html#scipy-interpolate-changes

> and functions from scipy.misc (bytescale, fromimage, imfilter, imread, imresize, imrotate, imsave, imshow, toimage) have been removed.

**Comment by yashshrikant99** [comment]
SciPy documentation makes it clear that scipy.misc.imread is deprecated and users must switch to imageio.imread.
