### ISSUE TITLE
Visualizing a trained IQN agent on Gopher game: iqn_network has no attribute 'probabilities'

### ISSUE THREAD

**Issue by dosssman** [google/dopamine#116]
Greetings.
Thank you very much for releasing this source code.

I am currently experimenting with the IQN implementation, namely by training it on the Atari's Gopher game.

Since I am not yet familiar with the IQN method, is there a way to get the probabilities distribution over the actions for an IQN agent. 
More precisely, they are required by the `example_viz_lib.py` script at lines 202~217:
```
    # Plot Q-values (DQN) or Q-value distributions (Rainbow).
    q_params = {'x': atari_plot.parameters['width'] // 2,
                'y': atari_plot.parameters['height'],
                'legend': action_names}
    if 'DQN' in self._agent.__class__.__name__:
      q_params['xlabel'] = 'Timestep'
      q_params['ylabel'] = 'Q-Value'
      q_params['title'] = 'Q-Values'
      q_params['get_line_data_fn'] = self._agent.get_q_values
      q_plot = line_plotter.LinePlotter(parameter_dict=q_params)
    else:
      q_params['xlabel'] = 'Return'
      q_params['ylabel'] = 'Return probability'
      q_params['title'] = 'Return distribution'
      q_params['get_bar_data_fn'] = self._agent.get_probabilities ### This line
      q_plot = bar_plotter.BarPlotter(parameter_dict=q_params)
```

**Comment by psc-g** [comment]
hi, thanks for pointing that out.
the `else` statement really only works for `Rainbow` agents, as the `get_probabilities` function is only defined for them: https://github.com/google/dopamine/blob/master/dopamine/utils/example_viz_lib.py#L119

IQN deals with quantiles, and the networks can output either `quantile_values` or `quantiles` (https://github.com/google/dopamine/blob/master/dopamine/agents/implicit_quantile/implicit_quantile_agent.py#L106)

to plot those you can subclass IQN (like is being done for DQN and Rainbow in `example_viz_lib.py`) and add a `get_quantile_values` method.

hope this helps!
