### ISSUE TITLE
maybe  state_shape and eval_mode should be pull up in DQNAgent

### ISSUE THREAD

**Issue by chenyw1990** [google/dopamine#12]
I want use DQNAgent to train my network with state shape [1, 14, 14, 5], state_shape is not the parameter of DQNAgent， I need  to modify the code in dqn_agent.py before to use it. so state shape as the parameter of DQNAgent maybe better.

ofter I train my network, I cannot change the eval mode of DQNAgent, so eval_mode as the parameter of DQNAgent maybe better.

**Comment by psc-g** [comment]
thanks for your feedback!
we will be collecting feature requests from users and incorporating them into our codebase as we move forward. this is a pretty common request, so stay tuned!
