### ISSUE TITLE
Tensorflow Attribute Error: module 'tensorflow_core._api.v2.train' has no attribute 'RMSProp Optimizer'

### ISSUE THREAD

**Issue by ThomasZav** [google/dopamine#121]
After conducting all the given steps on installation when I run ,

python -um dopamine.discrete_domains.train \
  --base_dir=/tmp/dopamine \
  --gin_files='dopamine/agents/dqn/configs/dqn.gin'

I get the following  error,

in line 97, in DQN Agent
              optimizer=tf.train.RMSPropOptimizer(
Attribute Error: module 'tensorflow_core._api.v2.train' has no attribute 'RMSProp Optimizer'

How could we solve this problem?

**Comment by wendersonj** [comment]
Did you get past it?

**Comment by wendersonj** [comment]
Did you get past it? @ThomasZav

**Comment by TobyGE** [comment]
Anyone got some progress???

**Comment by mgbellemare** [comment]
This should be an easy fix, stay tuned.

**Comment by psc-g** [comment]
could you let me know what version of tensorflow you have installed?
`pip show tensorflow-gpu` or `pip show tensorflow`

**Comment by ulyssesp** [comment]
It's RMSprop not RMSProp (notice the capital p)

**Comment by mhsmith** [comment]
Also, it's RMSprop, not RMSpropOptimizer. The full v2 name is [`tf.keras.optimizers.RMSprop`](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/RMSprop).
