### ISSUE TITLE
Cartpole error message

### ISSUE THREAD

**Issue by sunchipsster1** [google/dopamine#124]
Hello all! 
I was wondering if anyone knows how to resolve the following error message? This is taken from the Cartpole colab without changing any of the code. Does the dqn_config = ... need any values, or is it meant to be left without assignment? Thank you!

![image](https://user-images.githubusercontent.com/56416888/71061075-38e90500-2135-11ea-8c13-aae730c89a02.png)

**Comment by psc-g** [comment]
hi, apologies for this, it's due to our recent switch to keras, thanks for
pointing it out. i will be resolving this in the next few days. i'll report
on this thread once it's resolved, apologies for the inconvenience.

**Comment by sunchipsster1** [comment]
Thank you so much for the kind help! I do not know if the following is another instance of the recent switch to keras, but here is another error message, encountered in the "Agents" colab kindly provided by Dopamine--> keyError 'Asterix' 

![image](https://user-images.githubusercontent.com/56416888/71187846-dfc0c480-224d-11ea-9c72-fadd202ad601.png)

**Comment by psc-g** [comment]
i just pushed a new version of dopamine to pypi and i believe the cartpole
issue should be resolved now. can you try again and make sure that it
installs version 3.0.1 of dopamine-rl?
i'm taking a look at the agents colab now.

**Comment by psc-g** [comment]
i just tried the agents colab and it seems to work.
the `KeyError` you're getting is likely because you haven't run any of the colab's agents on `Asterix`.
