### ISSUE TITLE
Agents colab: gsutil

### ISSUE THREAD

**Issue by sunchipsster1** [google/dopamine#125]
Hello! In the agents colab (and also in other colabs) there is extensive use of gsutils. However the phrase "gsutil -q -m cp -R " does not seem to be recognized in Jupyter nor the Command prompt. A variety of other possibilities are recognized like gsutil cp -b -d -e, but not -q o r-m. Is there a correct version of gsutils that should be downloaded? Thanks! 

![image](https://user-images.githubusercontent.com/56416888/71233340-51872580-22c3-11ea-92c5-2583a39fd9c6.png)

**Comment by psc-g** [comment]
i'll have to look into this. we've only tested it on google colab but it's
possible there are differences when using Jupyter on the command prompt
directly.

**Comment by BigNosefan** [comment]
> Hello! In the agents colab (and also in other colabs) there is extensive use of gsutils. However the phrase "gsutil -q -m cp -R " does not seem to be recognized in Jupyter nor the Command prompt. A variety of other possibilities are recognized like gsutil cp -b -d -e, but not -q o r-m. Is there a correct version of gsutils that should be downloaded? Thanks!
> 
> ![image](https://user-images.githubusercontent.com/56416888/71233340-51872580-22c3-11ea-92c5-2583a39fd9c6.png)

I have the same issue with you. I downloaded that data into corresponding directory, and it works. Hope this can help you :>

**Comment by sunchipsster1** [comment]
Many thanks! I will try it out!
