### ISSUE TITLE
Cartpole colab: config and log file

### ISSUE THREAD

**Issue by sunchipsster1** [google/dopamine#126]
Hello! Thank you for all the kind help, from an enthusiastic user :)
After running through the Cartpole colab successfully from my own laptop in Linux (Jupyter), I wanted to run it again, but it appears that the second run-through, the script does not re-train and simply reuses the previous trained file. (see attached image below: second run-through, it took no time at all and simply said that the training was done). 

Is there any way to re-initialize everything? I tried deleted the dopamine folder and re-downloading the github attachment, but this did not change anything. I suspect that I am not successfully deleting the log files, or other associated dopamine files ... as I am unable to find out where the "'/tmp/colab_dopamine_run/dqn'" path is located. 

![image](https://user-images.githubusercontent.com/56416888/71235205-7e3e3b80-22c9-11ea-9c91-485a9f801a88.png)

**Comment by psc-g** [comment]
hi, you can do one of two things:

   1. delete the previous runs (`!rm -rf $BASE_PATH/dqn`)
   2. use a different directory for storing the new run's data. simply
   change the value of `DQN_PATH` when you run ```
   dqn_runner = run_experiment.create_runner(DQN_PATH, schedule=
   'continuous_train') ```

what's happening right now is that the agent looks in `$BASE_PATH/dqn` and
sees that there are checkpoints, so reloads those, only to find that the
stored iteration number is larger than the max number of iterations, so it
says "I'm done!" and quits.

**Comment by sunchipsster1** [comment]
Many thanks! It is resolved!
