### ISSUE TITLE
 mach-o, but built for simulator (not macOS)

### ISSUE THREAD

**Issue by liuyangvoid** [google/dopamine#14]
mac os High Sierra 10.13.6
error message:
OSError: dlopen(/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so, 6): no suitable image found.  Did find:
	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so: mach-o, but built for simulator (not macOS)
	/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/atari_py/ale_interface/build/libale_c.so: mach-o, but built for simulator (not macOS)

**Comment by psc-g** [comment]
can you provide the steps you followed to install, as well as the command line you ran that caused this error?

**Comment by psc-g** [comment]
closing this, as it's been a few months.
