### ISSUE TITLE
Evaluation Returns vs Training Returns

### ISSUE THREAD

**Issue by GoingMyWay** [google/dopamine#147]
Dear Dopamine developers,

This repo is really a great work for researchers to conduct fast experiments. I found there are two metrics in dopamine, one is training returns and another one is evaluation returns, and there is [a website](https://google.github.io/dopamine/baselines/plots.html#) of Dopamine providing comparisons between some baselines. For researchers to compare their idea with these baselines, which metric (training returns and evaluation returns) should be used?

**Comment by psc-g** [comment]
thanks for your message alexander,
as suggested in "Revisiting the Arcade Learning Environment: Evaluation
Protocols and Open Problems for General Agents" by Machado et al. (JAIR),
training returns should always be reported. in our white paper (
https://arxiv.org/abs/1812.06110) we found there is little difference
between training and eval returns.
ideally (without compute and time constraints) reporting both is always
better, but if you had to pick one, the two papers above suggest training
returns are the metric to report.

**Comment by GoingMyWay** [comment]
Thanks.
