### ISSUE TITLE
Diffenence against Rlax

### ISSUE THREAD

**Issue by JiahaoYao** [google/dopamine#155]
Hi, there are currently two lib for RL using Jax, Dopamine and Rlax. Might I ask what is the difference? Thanks!

**Comment by psc-g** [comment]
they are similar libraries but different and independent implementations. i
don't know too many details about relax, but from what i understand it is
mostly meant to be a collection of building blocks which you can use to
construct agents. on the other hand, in dopamine we provide monolithic
agents with tunable parameters that can modify their behaviour (for example
turning prioritized replay on or off in the rainbow agent).
hope this helps,

-psc

**Comment by 8bitmp3** [comment]
Thanks @psc-g and great episode on talkRL https://www.talkrl.com/episodes/pablo-samuel-castro 👍

> ... knowledge on distributional RL, bisimulation, the Dopamine RL Framework, TF-Agents, and much more!

I understand that, unlike Dopamine (Google Research), RLax has DeepMind-built dependencies like Haiku (similar to Sonnet in TensorFlow) and Optax.

Do you know if both libraries are meant for fast prototyping? The Dopamine example on CartPole with DQN and C51 appears to have less `import`s from the get-go.

**Comment by psc-g** [comment]
i can say that we built dopamine for fast prototyping, but i can't speak
for relax. you can ask the people on that repo :)

**Comment by JiahaoYao** [comment]
Thanks!
