### ISSUE TITLE
bundle_and_checkpoint bottleneck

### ISSUE THREAD

**Issue by mattgallivan** [google/dopamine#156]
When subclassing DQNAgent, my code seems to run slowest in the `bundle_and_checkpoint` and `unbundle` functions. If I overload these functions to simply do nothing, does this affect the DQN agent significantly other than not saving and loading checkpoints?

**Comment by psc-g** [comment]
the only thing that changes is that you won't be saving/loading checkpoints.
another alternative you may want to consider is to reduce the frequency at
which checkpoints are saved.

**Comment by mattgallivan** [comment]
Thanks!
