### ISSUE TITLE
Can DQNAgent run on multiple gpus?

### ISSUE THREAD

**Issue by bryanyuan1** [google/dopamine#179]
Hi! I am currently running the plain DQNAgent and hope to reproduce the baseline result. However, each iteration takes 30-40 minutes to finish. I am running the agent on AWS Sagemaker Studio. Is it possible to speed up training by using multiple gpus?

I think the agent uses only gpu:0 by default, because no matter how many gpus I have for my AWS notebook instance, the training speed is roughly the same. 

Thanks!

**Comment by psc-g** [comment]
hi, unfortunately the library by default does not support training a single
agent on multiple GPUs.
what i have found helpful is to use multiple GPUs to run the agent on
different seeds/games in parallel.

alternatively, if you're still in algorithm development phase (and still
exploring ideas), consider doing so in smaller environments like classic
control or MinAtar, as argued in: https://arxiv.org/abs/2011.14826

**Comment by bryanyuan1** [comment]
Thank you so much Pablo!

**Comment by psc-g** [comment]
no problem! if you're interested in running minatar with dopamine, you can
use this file as reference:
https://github.com/google-research/google-research/blob/master/tandem_dqn/minatar_env.py

with accompanying gin files:
https://github.com/google-research/google-research/tree/master/tandem_dqn/configs

**Comment by bryanyuan1** [comment]
Thanks will try that. Just curious, how much time did the baseline of DQN take to train for 200 iterations? How many timesteps per second did you have when training?

**Comment by psc-g** [comment]
on a p100 training DQN for 200 iterations took roughly 5 days.
