### ISSUE TITLE
DEPRECATION WARNING: Logger is being deprecated. Please switch to CollectorDispatcher!

### ISSUE THREAD

**Issue by FelipeMartins96** [google/dopamine#198]
I wanted to report this deprecation warning as I got it when running the training agents example commands from the docs, I'm not sure about how would I proceed to switch to CollectorDispatcher, not sure if there is a implementation available currently to use as reference.

**Comment by psc-g** [comment]
hi,
we are replacing the previous Logger
<https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/logger.py#L31>
with
a more flexible setup using CollectorDispatchers
<https://github.com/google/dopamine/blob/master/dopamine/metrics/collector_dispatcher.py>,
and this warning is just giving users advance notice.
you can safely ignore this warning, but if you'd like to get rid of it you
can just set this line to false (or set it with gin_bindings):
https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/run_experiment.py#L175

that being said, i agree it's a little cryptic, so we'll look into adding a
landing page that explains the transition.

**Comment by FelipeMartins96** [comment]
got it! thanks.
I will look into de docstring on collector_dispatcher.py to understand it better. So the agents of this repo are already using the CollectorDispatchers right?

**Comment by psc-g** [comment]
yup, they're already using CollectorsDispatcher, we just kept the legacy
logger activated for now, to avoid breaking people :)

**Comment by FelipeMartins96** [comment]
Thank you for the info, @psc-g; I will close this issue then, as it is not an issue, in fact :smile:
