### ISSUE TITLE
Jax agents not passing required argument to replay buffer constructor

### ISSUE THREAD

**Issue by tylerkastner** [google/dopamine#200]
`replay_capacity` and `batch_size` are required arguments for the `OutOfGraphReplayBuffer` constructor:
https://github.com/google/dopamine/blob/a2753dae222c75ae991758d4110a84bc01c3215f/dopamine/replay_memory/circular_replay_buffer.py#L104-L108
However they are not being passed in the `_build_replay_buffer` method of any Jax agent:
https://github.com/google/dopamine/blob/a2753dae222c75ae991758d4110a84bc01c3215f/dopamine/jax/agents/dqn/dqn_agent.py#L350-L357
This appears to only affect Jax agents, non-Jax agents use the `WrappedReplayBuffer` constructor for which `replay_capacity` and `batch_size` are not required arguments.

**Comment by psc-g** [comment]
hi tyler,
these are injected via gin bindings, e.g. here:
https://github.com/google/dopamine/blob/master/dopamine/jax/agents/dqn/configs/dqn.gin#L36

if you remove those lines from the gin files you'll see that you will get
an error.

**Comment by tylerkastner** [comment]
Ah that does it, thanks!
