### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by xenu256** [google/dopamine#22]
I don't get why you keep using Python 2?

https://pythonclock.org/

**Comment by mgbellemare** [comment]
Dopamine is designed with Python 3 in mind, but we found the installation instructions for other packages to sometimes fail when using Python 3.7. Almost certainly you should be able to make it work without too much trouble.

**Comment by psc-g** [comment]
in particular, it seems like installing with python 3.6 should work: https://github.com/GoogleCloudPlatform/tensorflow-without-a-phd/issues/18

**Comment by kjthedj** [comment]
HI
I am facing the following issue with installing dopamine-rl for 3.7:-
`ERROR: Ignored the following versions that require a different python version: 0.12.0 Requires-Python >=3.8; 0.12.0rc1 Requires-Python >=3.8; 0.12.1 Requires-Python >=3.8; 0.4.0 Requires-Python >=3.8; 0.4.1 Requires-Python >=3.8; 0.4.10 Requires-Python >=3.8; 0.4.11 Requires-Python >=3.8; 0.4.12 Requires-Python >=3.8; 0.4.13 Requires-Python >=3.8; 0.4.14 Requires-Python >=3.9; 0.4.15 Requires-Python >=3.9; 0.4.16 Requires-Python >=3.9; 0.4.17 Requires-Python >=3.9; 0.4.18 Requires-Python >=3.9; 0.4.19 Requires-Python >=3.9; 0.4.2 Requires-Python >=3.8; 0.4.20 Requires-Python >=3.9; 0.4.21 Requires-Python >=3.9; 0.4.22 Requires-Python >=3.9; 0.4.23 Requires-Python >=3.9; 0.4.24 Requires-Python >=3.9; 0.4.25 Requires-Python >=3.9; 0.4.26 Requires-Python >=3.9; 0.4.27 Requires-Python >=3.9; 0.4.28 Requires-Python >=3.9; 0.4.29 Requires-Python >=3.9; 0.4.3 Requires-Python >=3.8; 0.4.30 Requires-Python >=3.9; 0.4.31 Requires-Python >=3.10; 0.4.4 Requires-Python >=3.8; 0.4.5 Requires-Python >=3.8; 0.4.6 Requires-Python >=3.8; 0.4.7 Requires-Python >=3.8; 0.4.8 Requires-Python >=3.8; 0.4.9 Requires-Python >=3.8; 0.7.4 Requires-Python >=3.9; 0.7.5 Requires-Python >=3.9; 0.8.0 Requires-Python >=3.9; 0.8.1 Requires-Python >=3.9; 0.8.2 Requires-Python >=3.9; 0.8.3 Requires-Python >=3.9; 0.8.4 Requires-Python >=3.9; 0.8.5 Requires-Python >=3.9
ERROR: Could not find a version that satisfies the requirement jaxlib>=0.3.15 (from versions: none)
ERROR: No matching distribution found for jaxlib>=0.3.15
`
Was wondering if you had any ideas about what may be causing this and how to fix it in that sense?
