### ISSUE TITLE
Two player games

### ISSUE THREAD

**Issue by doas3140** [google/dopamine#23]
Is it possible to apply this framework for two player zero sum game environments? Any tips for doing so would be appreciated.

**Comment by daggertye** [comment]
This is a field called multi-agent rl. Specifically, for this framework (which is single player), transferring requires to agent to treat opposing players as part of the environment.  This often doesn't work in practice, but can sometime work out (self play). For more information, I would recommend researching that field. A good resource is here: https://github.com/LantaoYu/MARL-Papers.

**Comment by mgbellemare** [comment]
Dopamine doesn't support multiple agents in its current form (nor does the Arcade Learning Environment) -- but as @daggertye pointed out, there's now plenty of results applying RL algorithms such as DQN and Rainbow to multiagent settings. So, you could get something going for yourself -- it just would take extra engineering.

**Comment by RFAli** [comment]
If someone is still looking for multi-agent support in Dopamine, they can refer to the hanabi learning environment ([Rainbow Agent](https://github.com/deepmind/hanabi-learning-environment/blob/master/hanabi_learning_environment/agents/rainbow/rainbow_agent.py), [DQN Agent](https://github.com/deepmind/hanabi-learning-environment/blob/master/hanabi_learning_environment/agents/rainbow/dqn_agent.py)) which has a "_fork of the original Dopamine code incorporating changes for the multiplayer setting and the Hanabi Learning Environment_." This might be of some help.
