### ISSUE TITLE
Logging and checkpointing is better done on a time interval basis instead of per iteration basis

### ISSUE THREAD

**Issue by dev-matan-tsuberi** [google/dopamine#25]
Checkpointing is done to not repeat time consuming training, it should happen at regular time intervals. Logs can blow up in size if each iteration does not take a lot of time.
I recommend logging every 0.5 secs and checkpointing every 5 mins

**Comment by psc-g** [comment]
thanks for your feedback!  we'll take it into consideration as we improve dopamine.
