### ISSUE TITLE
Required tensorflow  version and cuda version are which one

### ISSUE THREAD

**Issue by fuxianh** [google/dopamine#26]
Can it work in tensorflow version <= 1.4.1 and cuda version <= 8.0 ?

**Comment by psc-g** [comment]
it is supported by tensorflow 2.7 and upwards (although there are some issues with 3.7). we have not tested it on earlier versions so we can't make any guarantees. but try it out and see! :)
the cuda compatibility is determined by its compatibility with tensorflow.
