### ISSUE TITLE
won't work without square observation shape

### ISSUE THREAD

**Issue by M00NSH0T** [google/dopamine#29]
I'm trying to adapt this to a non-atari environment that has simple, flat 1d observations, however the code, while commented to suggest you can use a tuple OBSERVATION_SHAPE, breaks down when you try to use anything other than a square observation space due to the following lines:

`state_shape = [1, OBSERVATION_SHAPE, OBSERVATION_SHAPE, STACK_SIZE]
self.state = np.zeros(state_shape)`

you get a "TypeError: 'tuple' object cannot be interpreted as an integer" unless OBSERVATION_SHAPE is anything other than an integer. However, the docs for the replay buffer indicate we should be able to use a tuple for observation_shape instead:

"observation_shape: tuple or int. If int, the observation is assumed to be a 2D square."

I should be able to work through this fairly quickly, but you may want to address this so users can more easily use this in experiments that don't involve playing atari games.

**Comment by psc-g** [comment]
hi, thanks for the feedback. and yes, this is something we've heard from multiple users, so we'll try to support it soon!

**Comment by M00NSH0T** [comment]
Great! thanks. It turns out solving this isn't as straightforward as I hoped since the observation_shape is used in so many modules either directly or indirectly... I spent most of the morning trying to wedge my flat observation space through. Hopefully, I'll have it sorted out this afternoon.

Thanks for providing this by the way. I'm really happy to see an official implementation of Rainbow, in particular.

**Comment by M00NSH0T** [comment]
@pathway thank you very much! That seems to have done the trick.
