### ISSUE TITLE
IMPALA Example

### ISSUE THREAD

**Issue by bionicles** [google/dopamine#31]
Would it too hard to add a working example of the cool IMPALA Trainer?

Also, how do you hook IMPALA to custom Envs and Actors?

Thanks in advance!

**Comment by pathway** [comment]
Meanwhile you can find IMPALA here: https://github.com/deepmind/scalable_agent

**Comment by psc-g** [comment]
at this point dopamine does not include an implementation of impala. see deepmind's open source implementation linked above.
