### ISSUE TITLE
question: trouble loading 'content'

### ISSUE THREAD

**Issue by yangliu2** [google/dopamine#33]
when loading content using `experimental_data = colab_utils.load_baselines('/content')`
I got this error `You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat`.
I'm not sure what's wrong. I ran this on my local computer. I have 'c51, dqn, implicit_quantile, quantile, rainbow' in 'content' folder. Is this pandas related problem?

**Comment by yangliu2** [comment]
Thanks. When will Google switch to python? The core developer is going to retire it.

**Comment by Jarvis-K** [comment]
I don't know how long the team will merge my pull request.but you can just simply modify like my pull request ,then rebuild it from source use  `python3 setup.py install`.Then you can load baselines with no errors.
But by the way ,if u build from source ,then try not reference colab code to modify your own codes,cause the dopamine-rl version used in it is lower than the source,it hasn't been modified for now.

**Comment by yangliu2** [comment]
I just installed python2.7 and run this. It still have the same problem. Do you have any thoughts?

**Comment by psc-g** [comment]
this is running on your local computer? the colab utilities have really only been tested on colab.research.google.com.

if you provide your setup and command lines used i can try to reproduce.

**Comment by KaixiangLin** [comment]
A quick fix:

add following lines after this line in notebook:  ```sample_data['run_number'] = 1```
```
sample_data['run_number'] = sample_data['run_number'].astype("float64")
sample_data['iteration'] = sample_data['iteration'].astype("float64")
sample_data['train_episode_returns'] = sample_data['train_episode_returns'].astype(
    "float64")
```
Similarly, add following lines after this [line](https://github.com/google/dopamine/blob/b4341f9cf62ddcf986241f3df879235c9105e679/dopamine/colab/utils.py#L78) in  colab.utils.py

```
single_agent_data['run_number'] = single_agent_data['run_number'].astype("float64")
single_agent_data['iteration'] = single_agent_data['iteration'].astype("float64")
single_agent_data['train_episode_returns'] = single_agent_data['train_episode_returns'].astype(
                    "float64")
```
Then you should be able to re-plot the results.

**Comment by xavigonzalvo** [comment]
This problem seems to persist in a [colab](https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb#scrollTo=EFY3tTITHugq) when loading the baseline data:

    experimental_data = colab_utils.load_baselines('/content')

Error is:

    ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat

**Comment by psc-g** [comment]
thanks for pointing this out. i've reproduced this error on my end and have a fix that will go out soon.

**Comment by psc-g** [comment]
this was fixed [here](https://github.com/google/dopamine/commit/834c4b856c0cab5261364d26fde281cb850974ce)
