### ISSUE TITLE
API doc generation

### ISSUE THREAD

**Issue by zhaoermosi** [google/dopamine#35]
May I have a quick question about how is this set of markdown api doc generated?

Thanks

**Comment by smoitra87** [comment]
@zhaoermosi the api doc is generated using a custom script. We push infrequently so it's possible that the documentation is stale. Anything that catches your eye?

**Comment by zhaoermosi** [comment]
Thank you for the response. The apidoc looks so good that I wonder if it is possible to share the script as a importable module :)

**Comment by psc-g** [comment]
hi, unfortunately the tools we use for generating the docs are not (yet) externally available.
