### ISSUE TITLE
How do i customize this for my application

### ISSUE THREAD

**Issue by Sumanharapanahalli** [google/dopamine#38]
Hi guys,

I think this is a basic question but still posting it here. 

If i want to use this frame work for my own problem ex- to Solve 2048, where so i start with. 

yes I am looking at beginners guide or some thing same.

**Comment by psc-g** [comment]
hi,
support for generic environments is something we're working on, but we don't have an exact timeline for release. stay tuned, as we will announce it in the "what's new" section of the main page when it's ready!
