### ISSUE TITLE
Issue when creating example form colab.

### ISSUE THREAD

**Issue by yakotaki** [google/dopamine#39]
I'm trying to run https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb
on local machine. 

I got this error for both examples 

/home/lukas/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
[2018-10-14 13:18:26,861] Making new env: AsterixNoFrameskip-v0
Traceback (most recent call last):
  File "/home/lukas/dopamine/dopamine/agents/luska_1/luska_1.py", line 51, in <module>
    max_steps_per_episode=100)
  File "/home/lukas/anaconda3/lib/python3.6/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lukas/anaconda3/lib/python3.6/site-packages/gin/utils.py", line 48, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 2, in raise_from
  File "/home/lukas/anaconda3/lib/python3.6/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lukas/dopamine/dopamine/atari/run_experiment.py", line 157, in __init__
    self._agent = create_agent_fn(self._sess, self._environment, summary_writer=self._summary_writer)
TypeError: create_random_dqn_agent() got an unexpected keyword argument 'summary_writer'
  In call to configurable 'Runner' (<function Runner.__init__ at 0x7f9b5b24b6a8>)

Thanks!

**Comment by MishaLaskin** [comment]
I got the same error when running colab notebook

**Comment by psc-g** [comment]
we have only tested this running on colab.research.google.com.
can you provide the full command you used to run it locally?

**Comment by Doc-Scott** [comment]
Getting same/similar error too 

`TypeError: create_basic_agent() got an unexpected keyword argument 'summary_writer'
  In call to configurable 'Runner' (<function Runner.__init__ at 0x7f5bd2e1f510>)`

This is when running a notebook that has been previously run and worked OK for other people. 
The notebook is here:

https://github.com/llSourcell/Google_Dopamine_LIVE/blob/master/Google_Dopamine_(LIVE)%20(1).ipynb

The full error message: 

`---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-50-215986982378> in <module>()
     61                                       training_steps=10,
     62                                       evaluation_steps=10,
---> 63                                       max_steps_per_episode=100)

/usr/local/lib/python3.6/dist-packages/gin/config.py in wrapper(*args, **kwargs)
   1030         scope_info = " in scope '{}'".format(scope_str) if scope_str else ''
   1031         err_str = err_str.format(name, fn, scope_info)
-> 1032         utils.augment_exception_message_and_reraise(e, err_str)
   1033 
   1034     return wrapper

/usr/local/lib/python3.6/dist-packages/gin/utils.py in augment_exception_message_and_reraise(exception, message)
     46   if six.PY3:
     47     ExceptionProxy.__qualname__ = type(exception).__qualname__
---> 48     six.raise_from(proxy.with_traceback(exception.__traceback__), None)
     49   else:
     50     six.reraise(proxy, None, sys.exc_info()[2])

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

/usr/local/lib/python3.6/dist-packages/gin/config.py in wrapper(*args, **kwargs)
   1007 
   1008       try:
-> 1009         return fn(*new_args, **new_kwargs)
   1010       except Exception as e:  # pylint: disable=broad-except
   1011         err_str = ''

/usr/local/lib/python3.6/dist-packages/dopamine/atari/run_experiment.py in __init__(self, base_dir, create_agent_fn, create_environment_fn, game_name, sticky_actions, checkpoint_file_prefix, logging_file_prefix, log_every_n, num_iterations, training_steps, evaluation_steps, max_steps_per_episode)
    162                             config=tf.ConfigProto(allow_soft_placement=True))
    163     self._agent = create_agent_fn(self._sess, self._environment,
--> 164                                   summary_writer=self._summary_writer)
    165     self._sess.run(tf.global_variables_initializer())
    166 

TypeError: create_basic_agent() got an unexpected keyword argument 'summary_writer'
  In call to configurable 'Runner' (<function Runner.__init__ at 0x7f5bd2e1f510>)`

**Comment by Doc-Scott** [comment]
cool, thanks @psc-g . I was running it on colab.research.google.com. 
Not sure I have the power to run it locally as no GPU. 
Any idea how long until it will be updated there?

**Comment by psc-g** [comment]
it already is updated there: https://colab.sandbox.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb
