### ISSUE TITLE
ImportError: No module named gin.tf

### ISSUE THREAD

**Issue by changzeng** [google/dopamine#4]
![image](https://user-images.githubusercontent.com/11350222/44722677-5f2e0000-ab00-11e8-9200-855b9617762b.png)

**Comment by psc-g** [comment]
did you run `pip install gin-config`?

**Comment by changzeng** [comment]
sorry this is my first time see this package. i don't know the full name of this package

**Comment by smoitra87** [comment]
You might find the following install instructions helpful. - https://github.com/google/dopamine/blob/master/README.md#ubuntu
