### ISSUE TITLE
Scalability

### ISSUE THREAD

**Issue by pathway** [google/dopamine#44]
In considering this framework for a practical project, it was not clear to me how to scale it up.

I think it would need a distributed prioritised replay/Ape-X at minimum.

I was considering using VecEnv from OpenAI, but even then we would need a thread-safe prioritised replay.

I looked for ape-x implementations on github but didnt see one I liked enough to try to integrate.

I bet this library would see a lot more use if it had a nice scale up story.

**Comment by pathway** [comment]
And it would be relatively easy to add a regular replay thread-safe, but without prioritization performance would not be good.
Thread-safe prioritized replay with sum tree etc. would take more care.

**Comment by psc-g** [comment]
thanks!
the main focus in our initial offering was nimbleness for fast experimental iteration.
we've heard the request from a few people about being able to scale up, so it's something we're considering, although there's no timeline as to when we expect to be able to offer this.
