### ISSUE TITLE
Installation problem: No module named dopamine.atari

### ISSUE THREAD

**Issue by mojtabamozaffar** [google/dopamine#46]
Hi,

I am facing a problem with installing and testing Dopamine. I am using an Ubuntu 18 OS and followed the exact instruction on the main page for "install via source" without getting any error. However, when I execute the commands on "Running tests" section I get errors

**Command:**
python tests/atari_init_test.py
**Output:**
ImportError: No module named dopamine.atari

**Command:**
python -um dopamine.atari.train \
  --agent_name=dqn \
  --base_dir=/tmp/dopamine \
  --gin_files='dopamine/agents/dqn/configs/dqn.gin'
**Output:**
Illegal instruction (core dumped)

I appreciate any suggestion on how I can solve this issue.

**Comment by Zhangzepuno1** [comment]
I got same problem, do you know how to deal with it?

**Comment by yakotaki** [comment]
try cd dopamine first.

**Comment by tjad** [comment]
Likely that this was due to the PYTHONPATH not being set correctly.
