### ISSUE TITLE
Why use np.array to create add_count

### ISSUE THREAD

**Issue by Seraphli** [google/dopamine#55]
I notice [here](https://github.com/google/dopamine/blob/bc66570375dd8d4ad785948e032a7662bb32e2a6/dopamine/replay_memory/circular_replay_buffer.py#L157) the replay buffer initialize `add_count` as a numpy array. But it used as int.
And in the test script [here](https://github.com/google/dopamine/blob/bc66570375dd8d4ad785948e032a7662bb32e2a6/dopamine/utils/test_utils.py#L34) and other agent test scripts like [this](https://github.com/google/dopamine/blob/bc66570375dd8d4ad785948e032a7662bb32e2a6/tests/dopamine/agents/rainbow/rainbow_agent_test.py#L411) initialize `add_count` as int.
So why use np.array in the first place?

**Comment by mgbellemare** [comment]
Hi, this is to simplify serialization.
