### ISSUE TITLE
[Question] How to utilize baseline score

### ISSUE THREAD

**Issue by Seraphli** [google/dopamine#56]
Hi, I checked the plot on the [page](https://google.github.io/dopamine/baselines/plots.html) provided by your guys. And I find the scores are quite different from the scores reported in the papers. Take the game `Asterix` for example. In the Rainbow paper, it reports Rainbow reaches 428,200.3 after 200 iterations. And in the IQN paper, it reports IQN reaches 342,016 after 200 iterations. But in the baselines, the scores are less than 20,000. So I wonder what the difference in the implement between the paper and the baselines, and how can I use the baselines score when I conduct some new researches.

BTW, I run a Rainbow experiment with the `rainbow_aaai.gin` configuration. And the score is better than the baseline. I haven't finished the experiment. Can this configuration reproduce the scores reported in the papers?

**Comment by mgbellemare** [comment]
Hello, these are results comparing algorithms on the Machado et al. (2018) standard settings. We also ran trial runs on published settings -- they should match, modulo variance in individual runs. These results should be available soon also.

Our Rainbow implementation only implements the three most important components compared in the paper, so it's possible that there are per-game differences.

**Comment by Seraphli** [comment]
Thanks for the reply! Looking forward to seeing these results.
