### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by shibl** [google/dopamine#61]
python tests/atari_init_test.py

Should be:

python tests/dopamine/atari_init_test.py

**Comment by Guar1** [comment]
Agree.

**Comment by mercuryrebornn** [comment]
Hey I already installed tor in my Kali but when a execute the brutforce it
says.. "install tor" . Why?

**Comment by mercuryrebornn** [comment]
Hey! I already installed tor in my Kali but when I executes the brutforce
it always commands "install tor". Why?

**Comment by suhailsinghbains** [comment]
Hi, Can I please take this up?
I am new here.

**Comment by psc-g** [comment]
this will be resolved with the new dopamine 2.0 push coming soon.
