### ISSUE TITLE
Training and eval log for non-sticky action mode?

### ISSUE THREAD

**Issue by KaixiangLin** [google/dopamine#65]
I wonder if it is possible to share the results for non-sticky action? 
Same as the Rainbow sample results plot in https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/load_statistics.ipynb# 

Also the evaluation results in samples/rainbow/{}_v4/logs, currently there are only training logs.
Thanks a lot!

**Comment by psc-g** [comment]
Hi kaixiang, sorry for the delay, still catching up after the holidays and rushing for ICML :).
I should have the logs for 5 independent runs of rainbow with stick_actions=False, i'll try to put them up in the next week or so.
the colab you cite below is using stick_actions=True.

**Comment by KaixiangLin** [comment]
Thanks a lot for the reply!
Isn't the yellow curve with label 'Sample Rainbow' using "stick_actions=True"? 
I assume the v4 log corresponds to the mode non-sticky action mode, based on the following line
https://github.com/google/dopamine/blob/b4341f9cf62ddcf986241f3df879235c9105e679/dopamine/atari/run_experiment.py#L77
