### ISSUE TITLE
[Question] Non-Atari Gym docs/samples?

### ISSUE THREAD

**Issue by jheffez** [google/dopamine#76]
It says that "Dopamine 2.0 now supports general discrete-domain gym environments". Yet, from what I see, all the docs and examples are Atari-centric. How can we experiment with discrete OpenAI Gym environments (like the basic CartPole). How can we start? Is there a doc or example we can refer to? Specifically interested in C51 and Rainbow info. 
Thank you.

**Comment by psc-g** [comment]
we recently added an example colab here: https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/cartpole.ipynb

which shows how you can train cartpole with dqn and c51.

we also provide gin configuration files for dqn, c51, and rainbow for cartpole and acrobot. see, e.g.: https://github.com/google/dopamine/blob/master/dopamine/agents/rainbow/configs/rainbow_cartpole.gin

these are not necessarily the optimal settings for these problems, but the provide a reasonable starting point. rainbow in particular proved rather challenging to get good stable results on cartpole and acrobot. so do let us know if you find more optimal settings and we can update the default configs.

thanks!

**Comment by jheffez** [comment]
cool! I'll check it out

**Comment by jheffez** [comment]
I was able to run the jupyter notebook on my pc but after installing Atari.py. Would it be possible to remove the Atari.py dependency in future version?

**Comment by psc-g** [comment]
thanks for raising this, we fixed this here: https://github.com/google/dopamine/commit/5fad7e9def71380136a43161df2ab98663d9a407
