### ISSUE TITLE
Inconsistent checkpoint duration between checkpointer.py and dqn_agent.py

### ISSUE THREAD

**Issue by Chazzz** [google/dopamine#78]
Minor inconsistency here, DQNAgent in dqn_agent.py sets max_tf_checkpoints_to_keep=3, which is passed to its tf.train.Saver, while checkpointer.py sets CHECKPOINT_DURATION=4 which is then used in _clean_up_old_checkpoints. Consequently there's a 4 vs 3 mismatch in the checkpoint save directory. I believe these numbers should be the same, or better yet, driven by the same configuration value.

**Comment by psc-g** [comment]
thanks for raising this, this has been addressed here: https://github.com/google/dopamine/commit/53d3450a296ad9a4d97f36b1fb7ed07d11bfe4ad
