### ISSUE TITLE
how to use the compiled pickle files?

### ISSUE THREAD

**Issue by zzzkk2009** [google/dopamine#8]
The compiled pickle files are available here
We make use of these compiled pickle files in both agents and the statistics colabs.

I downloaded these files, but i don't know how to use them, can anyone help me.

**Comment by psc-g** [comment]
check out the colabs here: https://github.com/google/dopamine/tree/master/dopamine/colab
specifically the `agents` and `loading statistics` ones. you will see example code on how to load and visualize the data from the pkl files.

you can also use the code directly: https://github.com/google/dopamine/blob/master/docs/api_docs/python/utils/read_experiment.md
