### ISSUE TITLE
Does dopamine work with TextWorld?

### ISSUE THREAD

**Issue by hsm207** [google/dopamine#87]
[TextWorld ](https://github.com/Microsoft/TextWorld#playing-a-game-python--gym) has an interface to Open AI's gym framework.

Does this mean it's possible to train an agent in TextWorld using the algorithms in dopamine?

**Comment by psc-g** [comment]
yes, you should be able to as long as it's discrete state and action spaces.
you will likely have to define a new network for it (see the [cartpole](https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/gym_lib.py#L109) or [acrobot](https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/gym_lib.py#L244) ones, for example).

**Comment by MarcCote** [comment]
Hi, if anything is missing in TextWorld to support dopamine, I would be happy to help. :)

**Comment by mgbellemare** [comment]
Hi @MarcCote , thanks for the vote of confidence :) I think it should mostly work, but Dopamine isn't currently equipped with recurrent networks. So there might be some tooling required to e.g. deal with backpropagation through time. @vishaljain3991 has used TextWorld without Dopamine but with recurrent networks and might have input.

**Comment by MarcCote** [comment]
I see. I'm also worried about how we currently defined the `observation_space` and `action_space` for TextWorld Gym environments - both are subclasses of `gym.spaces.MultiDiscrete` where each categorical variable represents a word ID from the vocab (see [details](https://github.com/Microsoft/TextWorld/blob/master/textworld/gym/spaces/text_spaces.py#L86)).

So far, I don't think anyone has used those custom spaces, and I'm not sure they are ideal.

**Comment by mgbellemare** [comment]
Yes, fair point – that's probably more complicated. I would implement this by converting the observation in e.g. Dopamine's run_experiment before passing the vector to the agent. But again, extra piping.
