### ISSUE TITLE
Can I use keras in the dopamine network?

### ISSUE THREAD

**Issue by lichongcoco** [google/dopamine#94]
I saw that in atari_lib.py, tensorflow is used to define the network. May I use a custom keras neural network, can I do this?

**Comment by mgbellemare** [comment]
Hi, I think the only hurdle is whether Keras will work with make_template() -- I think the Keras mechanism for variable sharing is a little different.

**Comment by lichongcoco** [comment]
Thank you for your answer. Will you support keras later? Is there any plan for this?

**Comment by lichongcoco** [comment]
Thank you for your answer. Will you support keras later? Is there any plan for this?
After all, keras is very simple to use.

**Comment by mgbellemare** [comment]
There is, but I couldn't give you an ETA at the moment.
