### ISSUE TITLE
How to use the model in inference mode

### ISSUE THREAD

**Issue by MarcoMeter** [google/dopamine#95]
Hello,

how does one load the model for execution only (not training) to watch the trained behavior?
This is related to #71

**Comment by mgbellemare** [comment]
If you load the agent but run it in eval mode, I think that will do what you want (combined to #71).

**Comment by MarcoMeter** [comment]
How is the eval mode used? Setting the training steps to 0 causes a division by zero exception.

**Comment by mgbellemare** [comment]
That sounds like a bug -- I think probably just missing a check that if training_steps = 0, we shouldn't run the train phase. We already do this for the eval phase (when eval_steps = 0).

**Comment by MarcoMeter** [comment]
For the eval mode, are all checkpoints files necessary?
Like the checkpoints that store states can get really large.

**Comment by mgbellemare** [comment]
You should only need the last checkpoint -- the code keeps a few (3) around, in case the most recent checkpoint is corrupted.

**Comment by MarcoMeter** [comment]
I mean these kind of checkpoint files:

```
add_count_ckpt.19.gz
ckpt.19
invalid_range_ckpt.19.gz
sentinel_checkpoint_complete.19
$store$_action_ckpt.19.gz
$store$_observation_ckpt.19.gz
$store$_reward_ckpt.19.gz
sum_tree_ckpt.19.gz
tf_ckpt-19.data-00000-of-00001
tf_ckpt-19.index
tf_ckpt-19.meta
```

Are all relevant for the eval mode? Especially the $store$_observation_ckpt can comprise many gigabytes.

**Comment by psc-g** [comment]
The tf_ckpt* files are for restoring the network parameters, so you
definitely want those.
The other files are for restoring the replay buffer to the state it was at
when the checkpoint was saved.
If you're only doing inference for evaluation (i.e. not sampling batches
from the replay buffer to learn from) then you don't need those files.
