### ISSUE TITLE
Issue with two colabs.

### ISSUE THREAD

**Issue by ahmadgjh** [google/dopamine#99]
I'm trying to run:

[https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/load_statistics.ipynb](url)

[https://colab.research.google.com/github/google/dopamine/blob/master/dopamine/colab/agents.ipynb](url)

connected to hosted runtime.

I got this error when loading the baseline data for both of the colabs:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-57fe23da76bc> in <module>()
      1 get_ipython().system('gsutil -q -m cp -R gs://download-dopamine-rl/preprocessed-benchmarks/* /content/')
----> 2 experimental_data = colab_utils.load_baselines('/content')

/usr/local/lib/python3.6/dist-packages/dopamine/colab/utils.py in load_baselines(base_dir, verbose)
     79         if game in experimental_data:
     80           experimental_data[game] = experimental_data[game].merge(
---> 81               single_agent_data, how='outer')
     82         else:
     83           experimental_data[game] = single_agent_data

/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py in merge(self, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
   6387                      right_on=right_on, left_index=left_index,
   6388                      right_index=right_index, sort=sort, suffixes=suffixes,
-> 6389                      copy=copy, indicator=indicator, validate=validate)
   6390 
   6391     def round(self, decimals=0, *args, **kwargs):

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in merge(left, right, how, on, left_on, right_on, left_index, right_index, sort, suffixes, copy, indicator, validate)
     59                          right_index=right_index, sort=sort, suffixes=suffixes,
     60                          copy=copy, indicator=indicator,
---> 61                          validate=validate)
     62     return op.get_result()
     63 

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in __init__(self, left, right, how, on, left_on, right_on, axis, left_index, right_index, sort, suffixes, copy, indicator, validate)
    553         # validate the merge keys dtypes. We may need to coerce
    554         # to avoid incompat dtypes
--> 555         self._maybe_coerce_merge_keys()
    556 
    557         # If argument passed to validate,

/usr/local/lib/python3.6/dist-packages/pandas/core/reshape/merge.py in _maybe_coerce_merge_keys(self)
    981             elif ((is_numeric_dtype(lk) and not is_bool_dtype(lk))
    982                     and not is_numeric_dtype(rk)):
--> 983                 raise ValueError(msg)
    984             elif (not is_numeric_dtype(lk)
    985                     and (is_numeric_dtype(rk) and not is_bool_dtype(rk))):

ValueError: You are trying to merge on float64 and object columns. If you wish to proceed you should use pd.concat

How to fix it?

Thank you.

**Comment by psc-g** [comment]
this was fixed [here](https://github.com/google/dopamine/commit/834c4b856c0cab5261364d26fde281cb850974ce)
